In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [7]:
indep=dataset[['age', 'bp','al', 'su', 'bgr','bu','sc','sod','pot','hrmo', 'pc_normal', 'pcc_present','ba_present', 'htn_yes', 'dm_yes', 'cad_yes','appet_yes','pe_yes','ane_yes']]
dep=dataset['classification_yes']

In [8]:
indep

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,1,0,0,0,0,0,1,0,0

In [9]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [21]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [23]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
17 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Evangeline\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.9848813  0.98523864 0.97862369 0.97951715
        nan        nan 0.98525022 0.98250222 0.96991177 0.97960495]
  warnings.warn(

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [24]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [25]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 10}: 0.9924946382275899

In [26]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 1 81]]

In [27]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [28]:
from sklearn.metrics import roc_auc_score

In [29]:
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9979674796747968

In [30]:
table=pd.DataFrame.from_dict(re)

In [31]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003125,0.006249,0.000000,0.000000e+00,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
1,0.003125,0.006250,0.000000,0.000000e+00,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2,0.028145,0.006247,0.003119,6.237411e-03,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.985075,0.985507,0.968750,0.985075,1.000000,0.984881,0.009892,3
3,0.200476,0.006243,0.015710,6.996366e-05,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.971429,0.984615,0.985075,0.985075,0.985239,0.009045,2
4,0.018748,0.006250,0.006249,7.653254e-03,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.970588,0.952381,0.985075,0.985075,0.978624,0.016084,7
5,0.188730,0.014209,0.018789,6.491073e-03,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",0.985075,0.957746,0.984615,0.985075,0.985075,0.979517,0.010887,6
6,0.000000,0.000000,0.000000,0.000000e+00,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
7,0.000000,0.000000,0.000000,0.000000e+00,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
8,0.021873,0.007655,0.000000,0.000000e+00,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.970588,1.000000,0.985075,0.970588,0.985250,0.013154,1
9,0.179404,0.012549,0.015624,8.583069e-07,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.957746,0.984615,0.985075,0.985075,0.982502,0.013687,4
10,0.019045,0.006251,0.009332,7.619981e-03,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",0.969697,0.957746,0.968750,0.968750,0.984615,0.969912,0.008567,8
11,0.153702,0.006238,0.003125,6.249332e-03,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.957746,0.984615,0.985075,0.970588,0.979605,0.014353,5

In [32]:
age_input=float(input("Age:"))
bp_input=float(input("BP (mm/Hg):"))
SpecificGravity_input=float(input("Specific Gravity:"))
Albumin_input=int(input("Albumin:"))
Sugar_input=int(input("Sugar:"))
Blood_Glucose_Random_input=int(input("Blood Glucose Random (mgs/dl) : "))
Blood_Urea_input=int(input("Blood Urea (mgs/dl): "))
Serum_Creatinine_input=float(input("Serum Creatinine (mgs/dl): "))
Sodium_input=float(input("Soduim (mEq/L): "))
Potassium_input=float(input("Potassium(mEq/L: )"))
Haemoglobin_input=float(input("Haemoglobin (gms) : "))
Packed_Cell_Volume_input=int(input("Packed Cell Volume : "))
White_Blood_Cell_input=int(input("White Blood Cells: "))
Hypertension_input=int(input("Hypertension: "))
Diabetes_input=int(input("Diabetes: "))
Coronary_Artery_Disease=int(input("Coronary Artery Disease: "))
Appetite_input=int(input("Appetite: "))
Pedeal_Edema_input=int(input("Pedal Edema: "))
Anaemia_input=int(input("Anaemia: "))

Age:48
BP (mm/Hg):80
Specific Gravity:1.02
Albumin:1
Sugar:0
Blood Glucose Random (mgs/dl) : 121
Blood Urea (mgs/dl): 36
Serum Creatinine (mgs/dl): 1.2
Soduim (mEq/L): 135.2976
Potassium(mEq/L: )3.000617
Haemoglobin (gms) : 15.4
Packed Cell Volume : 44
White Blood Cells: 7800
Hypertension: 1
Diabetes: 1
Coronary Artery Disease: 0
Appetite: 1
Pedal Edema: 0
Anaemia: 0

In [33]:
# 1 means Chronic Kidney Disease
# 0 means no Chronic Kidney Disease

In [34]:
Future_Prediction=grid.predict([[age_input,bp_input,SpecificGravity_input,Albumin_input,Sugar_input,Blood_Glucose_Random_input,Blood_Urea_input, Serum_Creatinine_input,Sodium_input,Potassium_input,Haemoglobin_input, Packed_Cell_Volume_input,White_Blood_Cell_input,Hypertension_input, Diabetes_input,Coronary_Artery_Disease,Appetite_input, Pedeal_Edema_input,Anaemia_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

In [36]:
import pickle
filename="finalized_model_Random_Forest.sav"
pickle.dump(classifier,open(filename,"wb"))

In [37]:
loaded_model=pickle.load(open("finalized_model_Random_Forest.sav",'rb'))

In [38]:
result=loaded_model.predict([[48, 80, 1.02, 1, 0, 121, 36, 1.2, 135.2976, 3.000617, 15.4, 44, 7800, 1, 1, 0, 1, 0, 0]])

In [39]:
result

array([1])